### ISSUE TITLE
Or should we

### ISSUE THREAD

**Issue by dereuromark** [oldskool/WhoopsCakephp#21]
focus on making the one already in https://github.com/FriendsOfCake/awesome-cakephp#debugging the de facto one? https://github.com/gourmet/whoops

It would only need the bootstrap for autoloading IMO, otherwise it looks like the one here, right?

**Comment by oldskool** [comment]
That plugin looks pretty similar, yes. It does miss the bootstrap, but that can easily be added. The only other difference that I can see is that the ErrorHandler of gourmet's version always blocks showing an error when debug mode is off, whereas my implementation allows it if the plugin is also loaded on a non-debug environment. This could be useful if people want to use it for a staging environment and receive usable error reports from testers, rather than just "I get a 500 error". Other than that, it should do the same thing.

To be honest, I haven't looked at/used this repo in a long time. So if gourmet's version is more actively maintained I would have no problems with it to point people towards his repo instead.

**Comment by dereuromark** [comment]
No, it does not have that issue to be honest.
I tried it (see my sandbox), and if debug 0 it will behave exactly like cakephp default does :)
The renderer is not invoked in that case.

Yeah, you can link to that one and mark yours as abandoned if you want to.

**Comment by oldskool** [comment]
@dereuromark Yeah, I miswrote that a little. What I meant is that it always uses Cake's core ErrorHandler, whereas my handler doesn't check whether or not debug mode is enabled and allows the "PrettyPageErrorHandler" to be used in staging (or even production if you'd really want to) environments. The handler itself doesn't block that, you can decide wheter or not you load the plugin in debug mode only, or always.

Anyway, yeah I'll mark this repo as abondoned and link to gourmet's version instead.
