### ISSUE TITLE
cake3 branch bootstrapping

### ISSUE THREAD

**Issue by tanuck** [oldskool/WhoopsCakephp#7]
Hi,

Is there a better way to configure the plugin other than editing the if statement in your app bootstrap file? Could it be moved to a plugin bootstrap file and then use `Plugin::load('WhoopsCakephp', ['bootstrap' => true]);` ? Would there be an issue regarding 2 error handlers being registered sequentially?

Regards

**Comment by oldskool** [comment]
As far as I recall when I created the 3.x version it was not possible to register multiple handlers. That's why I went with this approach. But Cake3 has had much updates since then, so I'm not sure if this is still an actual problem, I'll try it out when I have a moment. Obviously a plugin-based bootstrap edit would be the most convenient way to go about this.

**Comment by oldskool** [comment]
@tanuck Seems to work now, added this in the [latest commit](https://github.com/oldskool/WhoopsCakephp/commit/5aabac793ca35f595c5c57ecc6d4513c931f5663) on the cake3 branch. Thanks for the suggestion! :+1:

**Comment by tanuck** [comment]
:+1:
